### ISSUE TITLE
Just an array

### ISSUE THREAD

**Issue by kipusoep** [khayll/jsmix#6]
Hi!

How would I use this when my json object is just an array, without an identifier?
Like so:

```javascript
[
   {
      "name": "John Doe"
   }
]
```

Btw nice little plug-in :-)

**Comment by khayll** [comment]
Hey Kip, in that case you could just simply do this:

var employees = jsonmix([{"name": "John Doe"}])
.withObject(Object, "*")
.build();

for(const employee of employees) console.log(employee.name)

Of course in a real situation instead of Object you'd want an Employee.

Regards,
Khayll

**Comment by kipusoep** [comment]
Thank you, works fine indeed!
I think this could be made clearer in the documentation, don't you agree?

**Comment by khayll** [comment]
agreed
